const start = document.getElementById("Start");

const start = document.getElementById("Quiz");

const question = document.getElementById("Question");

const counter = document.getElementById("Countainer");

const timeGauge = document.getElementById("TimeGauge");

const ChoiceA = document.getElementById("A");
const ChoiceB = document.getElementById("B");
const ChoiceC = document.getElementById("C");
const ChoiceD = document.getElementById("D");

const scoreContainer = document.getElementById("ScoreContainer");

let questions = [
    {
        Question : "What purpose does HTML serve?",
        ChoiceA: "It doesn't serve a purpose",
        ChoiceB: "It is the foundation for building a website",
        ChoiceC: 
    }
]
